nabu-pmac: use default-safe timeout with 90s wlan0 wait

diff --git a/base/overlay/usr/local/bin/nabu-pmac-set b/base/overlay/usr/local/bin/nabu-pmac-set
--- a/base/overlay/usr/local/bin/nabu-pmac-set
+++ b/base/overlay/usr/local/bin/nabu-pmac-set
@@ -24,8 +24,8 @@ mac="${first_byte_hex}:${mac_bytes[1]}:${mac_bytes[2]}:${mac_bytes[3]}:${mac_byt
 n=0
 while [ ! -e /sys/class/net/wlan0 ]; do
   n=$((n+1))
-  if [ $n -ge 15 ]; then
-    echo "wlan0 did not appear within 15s, aborting." >&2
+  if [ $n -ge 90 ]; then
+    echo "wlan0 did not appear within 90s, aborting." >&2
     exit 1
   fi
   sleep 1
