Update update-binary

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -67,35 +67,30 @@ ui_print "---------------------------------------------";
 ui_print " ";
 mkdir -p "$tmp/esp";
 
-if mount | grep -q "$esp_part"; then
+if mount | grep -q " $esp_part "; then
   ui_print "ESP partition is already mounted, forcing unmount...";
   umount -lf "$esp_part" || abort "Failed to unmount the ESP partition";
 fi;
 mount "$esp_part" "$tmp/esp" || abort "Failed to mount ESP partition";
 
-ui_print "Verifying present bootloader configration";
-if [ -f $BCD ] && ! $bcdctl --check $BCD 2>/dev/null | grep -q "testsigning";
-then
-  ui_print "Secure Boot configuration detected. Proceeding to disable Secure Boot.";
+ui_print "Verifying present bootloader configuration";
+if [ -f "$BCD" ] && ! $bcdctl --check "$BCD" 2>/dev/null | grep -q "testsigning"; then
+  ui_print "Secure Boot configuration detected. Proceeding to disable it.";
   umount -lf "$win_part" 2>/dev/null;
   mkdir -p "$tmp/win" && mount.ntfs "$win_part" "$tmp/win" || abort "Failed to mount Windows";
-  mkdir -p "$tmp/win/installer/efi";
   unzip -o "$ZIPFILE" "installer/*" -d "$tmp/win" || abort "Failed to extract installer files";
   unzip -o "$ZIPFILE" "efi/*" -d "$tmp/win/installer" || abort "Failed to extract installer into Windows";
   if ! ls "$tmp/win/installer/efi/"* >/dev/null 2>&1; then
     cp -rf "$tmp/esp/EFI/." "$tmp/win/installer/efi/" || abort "Failed to extract efi from esp";
     rm -rf "$tmp/win/installer/efi/Microsoft";
   fi;
+  umount -lf "$esp_part" || abort "Failed to unmount the ESP partition";
   dd if="$esp_part" of=/sdcard/esp_backup.img bs=64M || abort "Failed to backup esp image";
-  umount -lf "$esp_part" && $mkfs.fat -F32 -s1 "$esp_part" -n ESPNABU 2>/dev/null;
+  $mkfs.fat -F32 -s1 "$esp_part" -n ESPNABU || abort "Failed to format ESP partition";
   dd if="$tmp/win/installer/pe.img" of="$esp_part" bs=64M || abort "Failed to dump pe image";
-  dd if="${boot_part}${slot}" of="${tmp}/win/installer/boot.img" bs=64M || abort "Failed to dump boot image";
+  dd if="${boot_part}${slot}" of="$tmp/win/installer/boot.img" bs=64M || abort "Failed to dump boot image";
 else
-  ui_print "Un-secure boot configration found";
-  for i in "$tmp"/esp/[eE][fF][iI]/*; do
-    [ -e "$i" ] || continue; case ${i##*/} in [mM][iI][cC][rR][oO][sS][oO][fF][tT]) ;; *) rm -rf -- "$i";; esac
-  done
-  mkdir -p "$tmp/esp/EFI"
+  ui_print "Un-secure boot configuration found";
   unzip -o "$ZIPFILE" "efi/*" -d "$tmp/esp" || abort "Failed to extract efi"
 fi;
 
