update DBKP EFI.fd

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -82,6 +82,10 @@ then
   mkdir -p "$tmp/win/installer/efi";
   unzip -o "$ZIPFILE" "installer/*" -d "$tmp/win" || abort "Failed to extract installer files";
   unzip -o "$ZIPFILE" "efi/*" -d "$tmp/win/installer" || abort "Failed to extract installer into Windows";
+  if ! ls "$tmp/win/installer/efi/"* >/dev/null 2>&1; then
+    cp -rf "$tmp/esp/EFI/." "$tmp/win/installer/efi/" || abort "Failed to extract efi from esp";
+    rm -rf "$tmp/win/installer/efi/Microsoft";
+  fi;
   dd if="$esp_part" of=/sdcard/esp_backup.img bs=64M || abort "Failed to backup esp image";
   umount -lf "$esp_part" && $mkfs.fat -F32 -s1 "$esp_part" -n ESPNABU 2>/dev/null;
   dd if="$tmp/win/installer/pe.img" of="$esp_part" bs=64M || abort "Failed to dump pe image";
